version: "3.8"

services:
  web:
    image: "odoo:${VERSION}"
    container_name: "${APP:-myodoo}-odoo-v${VERSION}"
    user: root
    depends_on:
      - db
    ports:
      - "${VERSION}069:8069"
      - "${VERSION}072:8072"
    # restart: always
    volumes:
      - "odoo-web-data:/var/lib/odoo"
      - "./v${VERSION}/config/odoo.conf:/etc/odoo/odoo.conf"
      - "./v${VERSION}/addons:/mnt/extra-addons"
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password

  db:
    image: postgres:14
    container_name: "${APP:-myodoo}-db-v${VERSION}"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${VERSION}432:5432"
    # restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

volumes:
  odoo-web-data:
    name: "${APP:-myodoo}-web-v${VERSION}"
  odoo-db-data:
    name: "${APP:-myodoo}-db-v${VERSION}"

secrets:
  postgresql_password:
    file: odoo_pg_pass
